### ISSUE TITLE
create-release:  Error: unknown release chart status subchart

### ISSUE THREAD

**Issue by bagel-dawg** [replicatedhq/replicated-actions#29]
Snippet from the workflow:

```
jobs:
  push-to-replicated:
    runs-on: ubuntu-22.04
    outputs:
      channel-slug: ${{ steps.create-release.outputs.channel-slug}}
    steps:
      - uses: actions/checkout@v3

      - name: Define App Version
        run: echo "APP_VERSION=0.0.1-${GITHUB_REF_NAME//[^a-zA-Z0-9]/}.${GITHUB_RUN_ID}${GITHUB_RUN_ATTEMPT}" >> $GITHUB_ENV

      - name: Define Channel Name
        run: echo "CHANNEL_NAME=${{ github.ref_name }}-${GITHUB_RUN_ID}${GITHUB_RUN_ATTEMPT}" >> $GITHUB_ENV

      - name: Package helm chart
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/turbine-kots:/app \
            -v ${{ github.workspace }}/turbine:/chart \
            alpine/helm:3.9.4 \
            package -d /app/config /chart --dependency-update

      - name: Create Replicated Release
        id: create-release
        uses: replicatedhq/replicated-actions/create-release@v1
        with:
          app-slug: ${{ env.REPLICATED_APP }}
          api-token: ${{ env.REPLICATED_API_TOKEN }}
          yaml-dir: ./turbine-kots/config
          promote-channel: ${{ env.CHANNEL_NAME }}
```

Failed action: 
![image](https://github.com/replicatedhq/replicated-actions/assets/26511304/a3a97d65-8543-4e49-9c55-59a587898f58)
