### ISSUE TITLE
kots-install: failed to parse config values: unable to decode config values file: couldn't get version/kind

### ISSUE THREAD

**Issue by bagel-dawg** [replicatedhq/replicated-actions#32]
From what  I can tell we're providing valid YAML, yet kots-install fails immediately with the following error:
![image](https://github.com/replicatedhq/replicated-actions/assets/26511304/8ab183bc-7d4e-4675-bbe1-d1339fb4d9b4)

Actions yaml:
```
      - name: Deploy the app
        uses: replicatedhq/replicated-actions/kots-install@v1
        with:
          kubeconfig: ${{ steps.create-cluster.outputs.cluster-kubeconfig }}
          app-slug: ${{ env.REPLICATED_APP }}/${{ needs.push-to-replicated.outputs.channel-slug }}
          license-file: ${{ steps.create-customer.outputs.license-file }}
          app-version-label: ${{ env.APP_VERSION }}
          namespace: swimlane
          config-values: turbine-kots/testing/replicated-app-config.yml.tpl
```

Config YAML:
```
apiVersion: kots.io/v1beta1
kind: ConfigValues
metadata:
  name: turbine
spec:
  values:
    api_replicas:
      value: "1"
    is_ha:
      value: "0"
    mongo_admin_user_password:
      value: "rKguFJTj3_j,;2{:5v$u!@#$%^&*()-_=+/{}[]|:;<,>.?`~"
    mongo_admin_user_password_confirm:
      value: "rKguFJTj3_j,;2{:5v$u!@#$%^&*()-_=+/{}[]|:;<,>.?`~"
    mongo_external_service:
      value: "1"
    mongo_replicas:
      value: "1"
    mongo_swimlane_user_password:
      value: "rKguFJTj3_j,;2{:5v$u!@#$%^&*()-_=+/{}[]|:;<,>.?`~"
    mongo_swimlane_user_password_confirm:
      value: "rKguFJTj3_j,;2{:5v$u!@#$%^&*()-_=+/{}[]|:;<,>.?`~"
    mongo_volume_size:
      value: "30"
    postgres_operator:
      value: "1"
    postgresql_volume_size:
      value: "8"
    postgresql_replicas:
      value: "1"
    pgpool_replicas:
      value: "1"
    pip_config:
      value: W2dsb2JhbF0KdGltZW91dCA9IDYwCmluZGV4LXVybCA9IGh0dHBzOi8vcHlwaS5weXRob24ub3JnL3NpbXBsZS8K
    pip_config_upload:
      value: "1"
    swimlane_audit_logging:
      value: "1"
    swimlane_audit_logging_level:
      value: Debug
    swimlane_database_encrypt_key:
      value: "SwimAndSoar"
    swimlane_database_encrypt_key_confirm:
      value: "SwimAndSoar"
    swimlane_hostname:
      value: swimlane.example.com
    swimlane_enable_ingress:
      value: "1"
    task_replicas:
      value: "1"
    web_replicas:
      value: "1"
    report_replicas:
      value: "1"
    record_replicas:
      value: "1"
    tenant_replicas:
      value: "1"
    turbine_agent_gateway_replicas:
      value: "1"
    turbine_engine_replicas:
      value: "2"
    turbine_api_replicas:
      value: "1"
    turbine_agent_replicas:
      value: "1"
    turbine_webhook_agent_replicas:
      value: "1"
    turbine_logger_replicas_replicas:
      value: "1"
    turbine_rabbitmq_operator:
      value: "1"
    turbine_rabbitmq_replicas:
      value: "1"
    turbine_agent_rabbitmq_password:
      value: "SwimAndSoar"
    turbine_agent_rabbitmq_password_confirm:
      value: "SwimAndSoar"
    turbine_rabbitmq_volume_size:
      value: "10"
    set_pod_resources:
      value: "1"
    set_feature_management:
      value: "1"
    feature_management:
      value: |
        TEST_FEATURE_FLAG: "true"
    pod_resources_turbine_rabbitmq:
      value: |
        requests:
          cpu: 250m
          memory: 512Mi
        limits:
          memory: 512Mi
    swimlane_storage_class:
      value: "standard"
    turbine_rabbitmq_storage_class:
      value: "standard"
    postgresql_storage_class:
      value: "standard"
 ```
