### ISSUE TITLE
helm-install: local install does not seem possible

### ISSUE THREAD

**Issue by mnp** [replicatedhq/replicated-actions#52]
In helm-install, since `registry-username` and `registry-password` are required, it does not seem possible to install from only a local checked-out chart directory.  If local were allowed, I would expect those to be optional and some kind of `chart-path` argument would be used instead.

The action README could clarify this situation either way, since it does mention local but doesn't say how.

**Comment by marccampbell** [comment]
Agreed that we should update the docs here. It is possible today:

Here's an example:

```
      - id: helm-install
        uses: replicatedhq/compatibility-actions/helm-install@v1
        with:
          kubeconfig: ${{ steps.create-cluster.outputs.cluster-kubeconfig }}
          chart: ./my-chart-0.0.0-alpha.${{ steps.vars.outputs.sha_short }}/my-chart
          name: 'my-chart'
          version: 'alpha.0.0.0-${{ steps.vars.outputs.sha_short }}'
          namespace: 'my-namespace'
          helm-path: 'helm'
          values: |
            replicated:
              integration:
                licenseID: ${{ secrets.REPLICATED_LICENSE_ID }}
```
