### ISSUE TITLE
Correct `create-cluster` documentation w/r to node-groups and instance types

### ISSUE THREAD

**Issue by adamancini** [replicatedhq/replicated-actions#75]
Description: I'm not getting the GKE node type I requested, using the CI action.

```
Run replicatedhq/compatibility-actions/create-cluster@v1
  with:
    api-token: ***
    kubernetes-distribution: gke
    kubernetes-version: 1.28
    instance-type: e2-standard-8
    cluster-name: foo
    disk: 200
    ttl: 60m
    timeout-minutes: 12
    node-groups:
  - name: general
    disk: 100
    nodes: 1
  - name: persistent
    disk: 500
    nodes: 1
  - name: pipelines
    disk: 50
    nodes: 3
```

I expected five e2-standard-8 nodes but (at least according to the node labels, I get `node.kubernetes.io/instance-type=n2-standard-2`

```NAME                                               PURPOSE     TYPE           ARCH   TAINTS
gke-c11y-matrix-42919fa2-general-5f876d46-7tnf     general     n2-standard-2  amd64
gke-c11y-matrix-42919fa2-persistent-b32bc1eb-kvl0  persistent  n2-standard-2  amd64
gke-c11y-matrix-42919fa2-pipelines-eedc838e-c3d7   pipelines   n2-standard-2  amd64
gke-c11y-matrix-42919fa2-pipelines-eedc838e-jl9h   pipelines   n2-standard-2  amd64
gke-c11y-matrix-42919fa2-pipelines-eedc838e-rjbk   pipelines   n2-standard-2  amd64
```

Resolution:
you must specify the instance-type explicitly under node-groups, else it will be fallback to default value of n2-standard-2

```
node-groups: |
  - name: general
    disk: 50
    nodes: 1
    instance-type: e2-standard-8
  - name: persistent
    disk: 50
    nodes: 1
    instance-type: e2-standard-8
```

Documentation should take into account:
- If you give a nodegroup, you have to give instance type for each (which makes sense so they can differ)
- when you don't give any nodegroups, the top level instance-type is used
- some other fields of the nodegroup spec are not optional: that should be a mention the doc
